# Nome do seu workflow, que aparecerá na aba "Actions" do GitHub
name: Run Robot Framework Tests

# Gatilho (trigger): quando o workflow deve rodar?
on:
  push:
    branches: [ main, develop ] # Roda sempre que houver um push na branch main ou develop
  pull_request:
    branches: [ main ] # Roda também quando um Pull Request for aberto para a main

# Tarefas (jobs) a serem executadas
jobs:
  test:
    # O tipo de máquina virtual para rodar o job
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o seu código do repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4 # Atualizado para v4

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5 # Atualizado para v5
        with:
          python-version: '3.11'

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Roda os testes do Robot Framework
      - name: Run Robot Framework tests
        run: robot -d results tests/

      # 5. Faz o upload dos artefatos de teste usando v4
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: results/